# cypress_test_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CypressTestApi
  # Http response received.
  class HttpResponse < CoreLibrary::HttpResponse
  end
end
