# cypress_test_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class APIControllerTest < ControllerTestBase
  # Called only once for the class before any test has executed
  def setup
    setup_class
    @controller = @client.client
    @response_catcher = @controller.http_call_back
  end

  # Generates a new OAuth token with the specified scopes.
  def test_create_o_auth_token
    # Parameters for the API call
    body = nil

    # Perform the API call through the SDK function
    @controller.create_o_auth_token(body: body)

    # Test response code
    assert_equal(201, @response_catcher.response.status_code)
  end

  # This endpoint accepts a complex structure with multiple arrays.
  def test_test_endpointwith_arrays
    # Parameters for the API call
    body = nil

    # Perform the API call through the SDK function
    @controller.test_endpointwith_arrays(body: body)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)
  end

end