# cypress_test_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CypressTestApi
  # CustomEnum.
  class CustomEnum
    CUSTOM_ENUM = [
      # TODO: Write general description for VALUE1
      VALUE1 = 'VALUE1'.freeze,

      # TODO: Write general description for VALUE2
      VALUE2 = 'VALUE2'.freeze,

      # TODO: Write general description for VALUE3
      VALUE3 = 'VALUE3'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      CUSTOM_ENUM.include?(value)
    end
  end
end
