# cypress_test_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CypressTestApi
  # OAuth 2 scopes supported by the API
  class OAuthScopeOAuthACGEnum
    O_AUTH_SCOPE_O_AUTH_ACG_ENUM = [
      # TODO: Write general description for ENUM_FILE_REQUESTSREAD
      ENUM_FILE_REQUESTSREAD = 'file_requests.read'.freeze,

      # TODO: Write general description for ZAHRA
      ZAHRA = 'zahra'.freeze,

      # TODO: Write general description for TEST1
      TEST1 = 'test1'.freeze,

      # TODO: Write general description for SELECTION
      SELECTION = 'selection'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      O_AUTH_SCOPE_O_AUTH_ACG_ENUM.include?(value)
    end
  end
end
