# cypress_test_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CypressTestApi
  # API utility class
  class APIHelper < CoreLibrary::ApiHelper
  end
end
